// SPDX-License-Identifier: Apache-2.0

package main

import (
	"flag"

	"github.com/pkg/profile"

	"github.com/hajimehoshi/go2dotnet/gowasm2csharp"
)

var (
	flagWasm      = flag.String("wasm", "", "WebAssembly file generated by Go")
	flagNamespace = flag.String("namespace", "", "Namespace")
	flagProfile   = flag.Bool("profile", false, "Take profiles")
)

func main() {
	flag.Parse()
	if *flagProfile {
		defer profile.Start().Stop()
	}
	if err := gowasm2csharp.Generate(*flagWasm, *flagNamespace); err != nil {
		panic(err)
	}
}
