// SPDX-License-Identifier: Apache-2.0

package main

import (
	"flag"
	"log"
	"os"

	"github.com/pkg/profile"

	"github.com/hajimehoshi/go2dotnet/gowasm2csharp"
)

var (
	flagOut       = flag.String("out", ".", "Output directory")
	flagWasm      = flag.String("wasm", "", "WebAssembly file generated by Go")
	flagNamespace = flag.String("namespace", "", "Namespace")
	flagProfile   = flag.Bool("profile", false, "Take profiles")
)

func main() {
	flag.Parse()
	if *flagProfile {
		defer profile.Start().Stop()
	}

	if err := os.MkdirAll(*flagOut, 0755); err != nil {
		log.Fatal(err)
	}
	if err := gowasm2csharp.Generate(*flagOut, *flagWasm, *flagNamespace); err != nil {
		log.Fatal(err)
	}
}
