name: Go

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgl1-mesa-dev

    - uses: actions/setup-go@v1
      with:
        go-version: 1.15.5
      id: go
    - uses: actions/checkout@v2

    - name: Test stdlib
      working-directory: test/stdlib
      run: |
        ./run.sh fmt -test.v
        ./run.sh math -test.v
        ./run.sh math/bits -test.v
        ./run.sh runtime -test.v -test.short -test.run=^Test
        ./run.sh runtime/internal/atomic -test.v
        ./run.sh runtime/internal/math -test.v
        ./run.sh runtime/internal/sys -test.v
        ./run.sh sort -test.v
        ./run.sh sync -test.v
        ./run.sh sync/atomic -test.v
