name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v1
      with:
        go-version: 1.15.2
      id: go
    - uses: actions/checkout@v2

    - name: Test stdlib
      working-directory: test/stdlib
      run: |
        ./run.sh fmt -test.v -test.run=^Test
        ./run.sh math -test.v -test.run=^Test
        ./run.sh math/bits -test.v -test.run=^Test
        ./run.sh runtime/internal/atomic -test.v -test.run=^Test
        ./run.sh runtime/internal/math -test.v -test.run=^Test
        ./run.sh runtime/internal/sys -test.v -test.run=^Test
        ./run.sh sort -test.v -test.run=^Test
        ./run.sh sync -test.v -test.run=^Test
        ./run.sh sync/atomic -test.v -test.run=^Test

    - name: Test binding
      working-directory: test/binding
      run: |
        ./run.sh -test.v -test.run=^Test
