name: Go

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ['1.16.x', '1.17.x']
    name: Test with Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgl1-mesa-dev

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
        stable: false

    - name: Test stdlib
      working-directory: test/stdlib
      run: |
        ./run.sh fmt -test.v
        ./run.sh math -test.v
        ./run.sh math/big -test.v -test.short # TestLinkerGC doesn't work (#21)
        ./run.sh math/bits -test.v
        ./run.sh math/cmplx -test.v
        ./run.sh math/rand -test.v
        ./run.sh runtime -test.v
        ./run.sh runtime/debug -test.v
        ./run.sh runtime/internal/atomic -test.v
        ./run.sh runtime/internal/math -test.v
        ./run.sh runtime/internal/sys -test.v
        ./run.sh strconv -test.v
        ./run.sh strings -test.v
        ./run.sh sort -test.v
        ./run.sh sync -test.v
        ./run.sh sync/atomic -test.v
